- name: d8.helm-releases-resource-versions
  rules:
  - alert: HelmReleaseHasResourcesWithDeprecatedVersions
    expr: |
      max by (helm_release_name) ((max without(instance, pod, hook, job) (resource_versions_compatibility) == 1)
      * on (module) group_left()(count by(module)(max without(instance, pod, hook, job) (resource_versions_compatibility) == 1) < 50) ^ 0)
    for: 10m
    labels:
      tier: cluster
      severity_level: "9"
    annotations:
      plk_markup_format: markdown
      plk_protocol_version: "1"
      plk_create_group_if_not_exists__helm_release_resource_versions_deprecated: "HelmReleaseHasResourcesWithDeprecatedVersions,tier=cluster"
      plk_group_for__helm_release_resource_versions_deprecated: HelmReleaseHasResourcesWithDeprecatedVersions,prometheus=deckhouse
      summary: One of HELM-Releases contains at least one resource with unsupported apiVersion in kubernetes 1.22+
      description: |
        To see all resources please use the  expr `max without(instance, pod, hook, job, tier, module) (resource_versions_compatibility) == 1` in prometheus.
        For more details, please follow the link https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

        Deprecation guide: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

  - alert: ClusterHasProblemsWithHelmReleasesWithResourceVersions
    expr: |
      (count by (module) (resource_versions_compatibility == 1)) >= 50
    for: 10m
    labels:
      tier: cluster
      severity_level: "9"
    annotations:
      plk_markup_format: markdown
      plk_protocol_version: "1"
      plk_create_group_if_not_exists__cluster_has_problems_with_helm_releases_with_resource_versions: "ClusterHasProblemsWithHelmReleasesWithResourceVersions,tier=cluster"
      plk_group_for__cluster_has_problems_with_helm_releases_with_resource_versions: ClusterHasProblemsWithHelmReleasesWithResourceVersions,prometheus=deckhouse
      summary: One of HELM-Releases contains at least one resource with unsupported apiVersion in kubernetes 1.22+
      description: |
        To see all resources please use the  expr `max without(instance, pod, hook, job, tier, module) (resource_versions_compatibility) == 1` in prometheus.
        For more details, please follow the link https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

        Deprecation guide: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22
