{{- if (hasKey .Values.prometheus.internal.alertmanagers "internal") }}
  {{- range .Values.prometheus.internal.alertmanagers.internal }}
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ .name }}
  namespace: d8-monitoring
  {{- include "helm_lib_module_labels" (list . (dict "app" "alertmanager")) | nindent 2 }}
spec:
  replicas: 3
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: {{ .name }}
  {{- end }}
{{- end }}
